AllCops:
  Exclude:
    - 'nextcloud-ruby.gemspec'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 89

Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
